# Required env vars:
#   GCLOUD_SERVICE_KEY
#   GOOGLE_PROJECT_ID
#   GOOGLE_COMPUTE_ZONE
#   GOOGLE_CLUSTER_NAME
version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t eu.gcr.io/${GOOGLE_PROJECT_ID}/chewie-${CIRCLE_SHA1} .
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Set Google Cloud Config
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - run:
          name: Deploy to Google Cloud
          command: |
            gcloud docker -- push eu.gcr.io/${GOOGLE_PROJECT_ID}/chewie-${CIRCLE_SHA1}
            kubectl patch deployment gitbutler -p '{"spec":{"template":{"spec":{"containers":[{"name":"chewie","image":"eu.gcr.io/${GOOGLE_PROJECT_ID}/chewie-${CIRCLE_SHA1}"}]}}}}'
